
pipeline {
    agent any
    stages {
        stage('SonarQube Analysis') {
            steps {
                script {
                    def scannerHome = tool 'sonarscanner'
                    withSonarQubeEnv('sonarqube') {
                        sh """${scannerHome}/bin/sonar-scanner -D project.settings=pipeline/sonarqube/sonar-project.properties"""
                    }
                }
            }
        }
    }
}
